# Generated by Django 3.1.6 on 2021-02-17 06:51

import discordlogin.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discorduser',
            managers=[
                ('objects', discordlogin.managers.DiscordUserOAuth2Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='discorduser',
            old_name='discord_tag',
            new_name='discordTag',
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='lastLogin',
            field=models.DateTimeField(null=True),
        ),
    ]
