# Generated by Django 3.1.6 on 2021-02-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogin', '0002_auto_20210217_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discorduser',
            old_name='lastLogin',
            new_name='last_login',
        ),
    ]
