# Generated by Django 3.1.6 on 2021-02-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogin', '0003_auto_20210217_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='last_login',
            field=models.DateTimeField(),
        ),
    ]
