# Generated by Django 3.1.6 on 2021-02-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogin', '0004_auto_20210218_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='is_active',
        ),
    ]
